engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - '**.ts'
    - '**.js'
    - '**.css'
    - '**.scss'
checks:
  method-complexity:
    config:
      threshold: 7
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_paths:
  - 'data/datacreator.js'
  - 'frontend/src/assets/private/**/*'
  - 'Gruntfile.js'
  - '**/*conf.js'
