application:
  showGitHubLinks: false
  social:
    questionnaireUrl: null
  welcomeBanner:
    showOnFirstStart: false
challenges:
  safetyMode: enabled
  showSolvedNotifications: false
hackingInstructor:
  isEnabled: false
